// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovoProjeto.Infra.Data.Context;

namespace NovoProjeto.Infra.Data.Migrations
{
    [DbContext(typeof(NovoProjetoContext))]
    [Migration("20220106213044_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NovoProjeto.Domain.Models.AcaoInvestimento", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("715b8039-667c-4366-9f8b-34fc5dd965bb"))
                        .HasColumnName("ACAO_INVESTIMENTO_ID");

                    b.Property<string>("CodigoAcao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("CODIGO_ACAO");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_ALTERACAO");

                    b.Property<DateTime>("DataInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 1, 6, 18, 30, 44, 149, DateTimeKind.Local).AddTicks(6497))
                        .HasColumnName("DATA_INCLUSAO");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("RAZAO_SOCIAL");

                    b.Property<bool>("Validacao")
                        .HasColumnType("bit")
                        .HasColumnName("VALIDACAO");

                    b.HasKey("ID");

                    b.ToTable("TB_ACAO_INVESTIMENTO");

                    b.HasData(
                        new
                        {
                            ID = new Guid("23dc4f1d-e629-401b-88e5-c318c39d088c"),
                            CodigoAcao = "AAPL",
                            DataInclusao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RazaoSocial = "Apple Inc.",
                            Validacao = false
                        },
                        new
                        {
                            ID = new Guid("587577d8-9536-42e7-8812-6ec57709ddc8"),
                            CodigoAcao = "AMZN",
                            DataInclusao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RazaoSocial = "Amazon.com, Inc.",
                            Validacao = false
                        },
                        new
                        {
                            ID = new Guid("21681a43-4dec-4f8d-888d-c23b4c9dae66"),
                            CodigoAcao = "GOOG",
                            DataInclusao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RazaoSocial = "Alphabet Inc.",
                            Validacao = false
                        },
                        new
                        {
                            ID = new Guid("f3fce418-7b32-4349-aa40-1a8a7aac94a1"),
                            CodigoAcao = "FB",
                            DataInclusao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RazaoSocial = "Meta Platforms, Inc.",
                            Validacao = false
                        },
                        new
                        {
                            ID = new Guid("a60019f0-03d9-4a24-9067-e30fedaed429"),
                            CodigoAcao = "TSLA",
                            DataInclusao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RazaoSocial = "Tesla, Inc.",
                            Validacao = false
                        },
                        new
                        {
                            ID = new Guid("6f024bc4-1a16-4e05-8a23-5732d66b0d9d"),
                            CodigoAcao = "NFLX",
                            DataInclusao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RazaoSocial = "Netflix Inc.",
                            Validacao = false
                        },
                        new
                        {
                            ID = new Guid("dfc9d16a-3321-46e3-9188-5f4a13508a9d"),
                            CodigoAcao = "IBM",
                            DataInclusao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RazaoSocial = "International Business Machines Corporation",
                            Validacao = false
                        });
                });

            modelBuilder.Entity("NovoProjeto.Domain.Models.OperacaoInvestimento", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("bca2cc03-0613-4d01-9b12-dbb12ec95126"))
                        .HasColumnName("ACAO_INVESTIMENTO_ID");

                    b.Property<string>("CodigoAcao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("CODIGO_ACAO");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_ALTERACAO");

                    b.Property<DateTime>("DataInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 1, 6, 18, 30, 44, 185, DateTimeKind.Local).AddTicks(7648))
                        .HasColumnName("DATA_INCLUSAO");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("QUANTIDADE");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("RAZAO_SOCIAL");

                    b.Property<string>("TipoOperacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TIPO_OPERACAO");

                    b.Property<bool>("Validacao")
                        .HasColumnType("bit")
                        .HasColumnName("VALIDACAO");

                    b.Property<decimal>("ValorAcao")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR_ACAO");

                    b.Property<decimal>("ValorTotalOperacao")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR_TOTAL_OPERACAO");

                    b.HasKey("ID");

                    b.ToTable("TB_OPERACAO_INVESTIMENTO");
                });
#pragma warning restore 612, 618
        }
    }
}
