// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovoProjeto.Infra.Data.Context;

namespace NovoProjeto.Infra.Data.Migrations
{
    [DbContext(typeof(NovoProjetoContext))]
    [Migration("20220110154815_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NovoProjeto.Domain.Models.AcaoInvestimento", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("e921b47b-52ee-4071-a752-7364e7a4783d"))
                        .HasColumnName("ACAO_INVESTIMENTO_ID");

                    b.Property<string>("CodigoAcao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("CODIGO_ACAO");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_ALTERACAO");

                    b.Property<DateTime>("DataInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 1, 10, 12, 48, 15, 292, DateTimeKind.Local).AddTicks(7886))
                        .HasColumnName("DATA_INCLUSAO");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("RAZAO_SOCIAL");

                    b.Property<bool>("Validacao")
                        .HasColumnType("bit")
                        .HasColumnName("VALIDACAO");

                    b.HasKey("ID");

                    b.ToTable("TB_ACAO_INVESTIMENTO");

                    b.HasData(
                        new
                        {
                            ID = new Guid("3537879f-ed38-48e7-a2c6-b3db2f5af328"),
                            CodigoAcao = "AAPL",
                            DataInclusao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RazaoSocial = "Apple Inc.",
                            Validacao = false
                        },
                        new
                        {
                            ID = new Guid("347410f1-e07a-4728-bdab-4fb8dc864df5"),
                            CodigoAcao = "AMZN",
                            DataInclusao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RazaoSocial = "Amazon.com, Inc.",
                            Validacao = false
                        },
                        new
                        {
                            ID = new Guid("c2ac1ff2-a97d-4eed-9a20-9891867eae21"),
                            CodigoAcao = "GOOG",
                            DataInclusao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RazaoSocial = "Alphabet Inc.",
                            Validacao = false
                        },
                        new
                        {
                            ID = new Guid("3fe9d20e-260c-4272-8a2a-b15612a4a594"),
                            CodigoAcao = "FB",
                            DataInclusao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RazaoSocial = "Meta Platforms, Inc.",
                            Validacao = false
                        },
                        new
                        {
                            ID = new Guid("de583068-aa4f-49a9-8fa4-b29d610f6bf7"),
                            CodigoAcao = "TSLA",
                            DataInclusao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RazaoSocial = "Tesla, Inc.",
                            Validacao = false
                        },
                        new
                        {
                            ID = new Guid("f8c3178a-3920-463d-bc30-1ff181954407"),
                            CodigoAcao = "NFLX",
                            DataInclusao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RazaoSocial = "Netflix Inc.",
                            Validacao = false
                        },
                        new
                        {
                            ID = new Guid("28cb964c-e7e6-481d-b712-336f21008a6c"),
                            CodigoAcao = "IBM",
                            DataInclusao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RazaoSocial = "International Business Machines Corporation",
                            Validacao = false
                        });
                });

            modelBuilder.Entity("NovoProjeto.Domain.Models.OperacaoInvestimento", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("0dfdd6ea-20fa-42eb-ae9a-569e56dfb4d1"))
                        .HasColumnName("ACAO_INVESTIMENTO_ID");

                    b.Property<string>("CodigoAcao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("CODIGO_ACAO");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_ALTERACAO");

                    b.Property<DateTime>("DataInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 1, 10, 12, 48, 15, 302, DateTimeKind.Local).AddTicks(7442))
                        .HasColumnName("DATA_INCLUSAO");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("QUANTIDADE");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("RAZAO_SOCIAL");

                    b.Property<string>("TipoOperacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TIPO_OPERACAO");

                    b.Property<bool>("Validacao")
                        .HasColumnType("bit")
                        .HasColumnName("VALIDACAO");

                    b.Property<double>("ValorAcao")
                        .HasColumnType("float")
                        .HasColumnName("VALOR_ACAO");

                    b.Property<double>("ValorTotalOperacao")
                        .HasColumnType("float")
                        .HasColumnName("VALOR_TOTAL_OPERACAO");

                    b.HasKey("ID");

                    b.ToTable("TB_OPERACAO_INVESTIMENTO");
                });
#pragma warning restore 612, 618
        }
    }
}
