// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovoProjeto.Infra.Data.Context;

namespace NovoProjeto.Infra.Data.Migrations
{
    [DbContext(typeof(NovoProjetoContext))]
    [Migration("20220110155344_ValidacaoTrue")]
    partial class ValidacaoTrue
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NovoProjeto.Domain.Models.AcaoInvestimento", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("09efbfa4-27aa-45ae-b118-f7d43ad39c56"))
                        .HasColumnName("ACAO_INVESTIMENTO_ID");

                    b.Property<string>("CodigoAcao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("CODIGO_ACAO");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_ALTERACAO");

                    b.Property<DateTime>("DataInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 1, 10, 12, 53, 44, 93, DateTimeKind.Local).AddTicks(1467))
                        .HasColumnName("DATA_INCLUSAO");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("RAZAO_SOCIAL");

                    b.Property<bool>("Validacao")
                        .HasColumnType("bit")
                        .HasColumnName("VALIDACAO");

                    b.HasKey("ID");

                    b.ToTable("TB_ACAO_INVESTIMENTO");

                    b.HasData(
                        new
                        {
                            ID = new Guid("9dfeb225-bcd5-484b-93ac-9a6ac89ec9b8"),
                            CodigoAcao = "AAPL",
                            DataInclusao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RazaoSocial = "Apple Inc.",
                            Validacao = true
                        },
                        new
                        {
                            ID = new Guid("ea276203-7052-4460-b311-1fcdc92b7f5b"),
                            CodigoAcao = "AMZN",
                            DataInclusao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RazaoSocial = "Amazon.com, Inc.",
                            Validacao = true
                        },
                        new
                        {
                            ID = new Guid("eba9ddf2-1301-47b5-9068-7837b63641a8"),
                            CodigoAcao = "GOOG",
                            DataInclusao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RazaoSocial = "Alphabet Inc.",
                            Validacao = true
                        },
                        new
                        {
                            ID = new Guid("e4c00ff7-047a-4352-9422-518f04345de2"),
                            CodigoAcao = "FB",
                            DataInclusao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RazaoSocial = "Meta Platforms, Inc.",
                            Validacao = true
                        },
                        new
                        {
                            ID = new Guid("e4421514-4cd2-4fe5-be26-60ce02465783"),
                            CodigoAcao = "TSLA",
                            DataInclusao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RazaoSocial = "Tesla, Inc.",
                            Validacao = true
                        },
                        new
                        {
                            ID = new Guid("f0cd6974-2906-41b6-b635-aa7c0137ada3"),
                            CodigoAcao = "NFLX",
                            DataInclusao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RazaoSocial = "Netflix Inc.",
                            Validacao = true
                        },
                        new
                        {
                            ID = new Guid("3ce34685-39c6-4da2-8d6f-ebbf525c7b17"),
                            CodigoAcao = "IBM",
                            DataInclusao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RazaoSocial = "International Business Machines Corporation",
                            Validacao = true
                        });
                });

            modelBuilder.Entity("NovoProjeto.Domain.Models.OperacaoInvestimento", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("262eb2f2-fb94-4414-92fb-6f955aeb5021"))
                        .HasColumnName("ACAO_INVESTIMENTO_ID");

                    b.Property<string>("CodigoAcao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("CODIGO_ACAO");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_ALTERACAO");

                    b.Property<DateTime>("DataInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 1, 10, 12, 53, 44, 104, DateTimeKind.Local).AddTicks(864))
                        .HasColumnName("DATA_INCLUSAO");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("QUANTIDADE");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("RAZAO_SOCIAL");

                    b.Property<string>("TipoOperacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TIPO_OPERACAO");

                    b.Property<bool>("Validacao")
                        .HasColumnType("bit")
                        .HasColumnName("VALIDACAO");

                    b.Property<double>("ValorAcao")
                        .HasColumnType("float")
                        .HasColumnName("VALOR_ACAO");

                    b.Property<double>("ValorTotalOperacao")
                        .HasColumnType("float")
                        .HasColumnName("VALOR_TOTAL_OPERACAO");

                    b.HasKey("ID");

                    b.ToTable("TB_OPERACAO_INVESTIMENTO");
                });
#pragma warning restore 612, 618
        }
    }
}
